name: Main

on:
  push:
    branches: [main]

jobs:
  soundness:
    name: Soundness
    uses: hdtls/swift-ci/.github/workflows/soundness.yml@main
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

  unit-tests:
    name: Unit tests
    uses: hdtls/swift-ci/.github/workflows/unit_tests.yml@main
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    with:
      windows_6_0_enabled: true
      windows_6_1_enabled: true
      windows_nightly_release_enabled: true
      windows_nightly_main_enabled: true
