name: Main

on:
  push:
    branches: [main]

jobs:
  soundness:
    name: Soundness
    uses: hdtls/swift-ci/.github/workflows/soundness.yml@main
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

  unit-tests:
    name: Unit tests
    uses: hdtls/swift-ci/.github/workflows/unit_tests.yml@main
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    with:
      machine: "host"

      linux_5_9_enabled: false
      linux_5_10_enabled: false
      linux_6_0_enabled: false
      linux_6_1_enabled: false
      linux_nightly_release_enabled: false
      linux_nightly_main_enabled: false
      linux_build_command_options: "-Xswiftc -warnings-as-errors --explicit-target-dependency-import-check error"
      linux_nightly_main_build_command_options: "--explicit-target-dependency-import-check error"

      windows_6_0_enabled: false
      windows_6_1_enabled: false
      windows_nightly_release_enabled: true
      windows_nightly_main_enabled: true
      windows_build_command_options: "-Xswiftc -warnings-as-errors --explicit-target-dependency-import-check error"
      windows_nightly_main_build_command_options: "--explicit-target-dependency-import-check error"

  swiftpm:
    name: swiftpm
    uses: swiftlang/github-workflows/.github/workflows/swift_package_test.yml@main
    with:
      enable_linux_checks: false
      enable_windows_docker: false
      windows_exclude_swift_versions: "[{\"swift_version\": \"5.9\"}, {\"swift_version\": \"5.10\"}, {\"swift_version\": \"6.0\"}, {\"swift_version\": \"6.1\"}, {\"swift_version\": \"nightly-6.1\"}]"
