name: Matrix

on:
  workflow_call:
    inputs:
      name:
        type: string
        description: "The name of the workflow used for the concurrency group."
        required: true
      matrix_string:
        type: string
        description: "The test matrix definition."
        required: true

    secrets:
      PERSONAL_ACCESS_TOKEN:
        required: true

# We will cancel previously triggered workflow runs
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ inputs.name }}
  cancel-in-progress: true

jobs:
  execute-matrix:
    name: ${{ matrix.definitions.platform }} (${{ matrix.definitions.swift_version }} - ${{ matrix.definitions.os_version }})
    runs-on: ${{ matrix.definitions.runner }}
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(inputs.matrix_string) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          submodules: true

      - name: Run matrix job (Windows)
        timeout-minutes: 60
        run: |
          mkdir $env:TEMP\scripts
          echo @'
          $DebugPreference = "SilentlyContinue"
          $VerbosePreference = "SilentlyContinue"

          Set-PSDebug -Trace 1
          $Source = "C:\_w\work"

          # Run the command following `Invoke-Program`.
          # If that command returns a non-zero exit code, return the same exit code from this script.
          function Invoke-Program($Executable) {
            & $Executable @args 2>&1 5>$null

            if ($LastExitCode -ne 0) {
              exit $LastExitCode
            }
          }

          Invoke-Program swift --version
          Invoke-Program swift test --version
          Invoke-Program cd $Source

          if (-not [string]::IsNullOrEmpty("${{ secrets.PERSONAL_ACCESS_TOKEN }}")) {
            Invoke-Program git config --global --add url."https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/".insteadOf "https://github.com/"
          }

          ${{ matrix.definitions.pre_build_command }}
          Invoke-Program ${{ matrix.definitions.build_command }} ${{ matrix.definitions.build_command_options }}
          '@ >> $env:TEMP\scripts\run.ps1

          $Image = "${{ contains(matrix.definitions.swift_version, 'nightly') && 'swiftlang/swift' || 'swift' }}:${{ matrix.definitions.swift_version }}-${{ matrix.definitions.os_version }}"
          docker run -v ${{ github.workspace }}:C:\_w\work -v $env:TEMP\scripts:C:\_w\scripts -e CI=$env:CI -e GITHUB_ACTIONS=$env:GITHUB_ACTIONS -e SWIFT_VERSION=${{ matrix.definitions.swift_version }} $Image powershell.exe -NoLogo -File C:\_w\scripts\run.ps1
