name: Pull Request Validation (CI)

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  soundness:
    name: Soundness
    uses: hdtls/swift-ci/.github/workflows/soundness.yml@main
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    with:
      api_breakage_check_enabled: false
      format_check_enabled: false

  unit-tests:
    name: Unit tests
    uses: hdtls/swift-ci/.github/workflows/unit_tests.yml@main
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    with:
      linux_build_command_options: "-Xswiftc -warnings-as-errors --explicit-target-dependency-import-check error"
      linux_nightly_main_build_command_options: "--explicit-target-dependency-import-check error"
      linux_pre_build_command: |
        mkdir MyPackage
        cd MyPackage
        swift package init --type library
        swift build

      windows_6_0_enabled: true
      windows_6_1_enabled: true
      windows_nightly_release_enabled: true
      windows_nightly_main_enabled: true
      windows_build_command_options: "-Xswiftc -warnings-as-errors --explicit-target-dependency-import-check error"
      windows_nightly_main_build_command_options: "--explicit-target-dependency-import-check error"
      windows_pre_build_command: |
        mkdir MyPackage
        cd MyPackage
        swift package init --type library
        swift build
