name: Unit tests

on:
  workflow_call:
    inputs:
      macos_pre_build_command:
        type: string
        default: ""
      macos_build_command:
        type: string
        default: swift test
      macos_build_command_options:
        type: string
        description: "The default arguments passed to swift test in the macOS matrix job. override by versioned build_command_options."
        default: ""
      macos_5_9_enabled:
        type: boolean
        description: "Boolean to enable the macOS Swift 5.9 (Xcode 15.2) matrix job. Defaults to true."
        default: false
      macos_5_9_build_command_options:
        type: string
        description: "The arguments passed to swift test in the macOS Swift 5.9 (Xcode 15.2) matrix job."
        default: ""
      macos_5_10_enabled:
        type: boolean
        description: "Boolean to enable the macOS Swift 5.10 (Xcode 15.4) matrix job. Defaults to true."
        default: false
      macos_5_10_build_command_options:
        type: string
        description: "The arguments passed to swift test in the macOS Swift 5.10 (Xcode 15.4) matrix job."
        default: ""
      macos_6_0_enabled:
        type: boolean
        description: "Boolean to enable the macOS Swift 6.0 (Xcode 16.2) matrix job. Defaults to true."
        default: false
      macos_6_0_build_command_options:
        type: string
        description: "The arguments passed to swift test in the macOS Swift 6.0 (Xcode 16.2) matrix job."
        default: ""
      macos_6_1_enabled:
        type: boolean
        description: "Boolean to enable the macOS Swift 6.1 (Xcode 16.4) matrix job. Defaults to true."
        default: false
      macos_6_1_build_command_options:
        type: string
        description: "The arguments passed to swift test in the macOS Swift 6.1 (Xcode 16.4) matrix job."
        default: ""
      macos_6_2_enabled:
        type: boolean
        description: "Boolean to enable the macOS Swift 6.2 (Xcode 26) matrix job. Defaults to true."
        default: false
      macos_6_2_build_command_options:
        type: string
        description: "The arguments passed to swift test in the macOS Swift 6.2 (Xcode 26) matrix job."
        default: ""

      linux_pre_build_command:
        type: string
        default: ""
      linux_build_command:
        type: string
        default: swift test
      linux_build_command_options:
        type: string
        description: "The default arguments passed to swift test in the Linux matrix job. override by versioned build_command_options."
        default: ""
      linux_5_9_enabled:
        type: boolean
        description: "Boolean to enable the Linux 5.9 Swift version matrix job. Defaults to true."
        default: true
      linux_5_9_build_command_options:
        type: string
        description: "The arguments passed to swift test in the Linux 5.9 Swift version matrix job."
        default: ""
      linux_5_10_enabled:
        type: boolean
        description: "Boolean to enable the Linux 5.10 Swift version matrix job. Defaults to true."
        default: true
      linux_5_10_build_command_options:
        type: string
        description: "The arguments passed to swift test in the Linux 5.10 Swift version matrix job."
        default: ""
      linux_6_0_enabled:
        type: boolean
        description: "Boolean to enable the Linux 6.0 Swift version matrix job. Defaults to true."
        default: true
      linux_6_0_build_command_options:
        type: string
        description: "The arguments passed to swift test in the Linux 6.0 Swift version matrix job."
        default: ""
      linux_6_1_enabled:
        type: boolean
        description: "Boolean to enable the Linux 6.1 Swift version matrix job. Defaults to true."
        default: true
      linux_6_1_build_command_options:
        type: string
        description: "The arguments passed to swift test in the Linux 6.1 Swift version matrix job."
        default: ""
      linux_6_2_enabled:
        type: boolean
        description: "Boolean to enable the Linux 6.2 Swift version matrix job. Defaults to true."
        default: true
      linux_6_2_build_command_options:
        type: string
        description: "The arguments passed to swift test in the Linux 6.2 Swift version matrix job."
        default: ""
      linux_nightly_release_enabled:
        type: boolean
        description: "Boolean to enable the Linux nightly release/x.x Swift version matrix job. Defaults to true."
        default: true
      linux_nightly_release_build_command_options:
        type: string
        description: "The arguments passed to swift test in the Linux nightly release/x.x Swift version matrix job."
        default: ""
      linux_nightly_main_enabled:
        type: boolean
        description: "Boolean to enable the Linux nightly main Swift version matrix job. Defaults to true."
        default: true
      linux_nightly_main_build_command_options:
        type: string
        description: "The arguments passed to swift test in the Linux nightly main Swift version matrix job."
        default: ""

      windows_pre_build_command:
        type: string
        default: ""
      windows_build_command:
        type: string
        default: swift test
      windows_build_command_options:
        type: string
        default: ""
      windows_6_0_enabled:
        type: boolean
        description: "Boolean to enable the Windows 6.0 Swift version matrix job. Defaults to false."
        default: false
      windows_6_0_build_command_options:
        type: string
        description: "The arguments passed to swift test in the Windows 6.0 Swift version matrix job."
        default: ""
      windows_6_1_enabled:
        type: boolean
        description: "Boolean to enable the Windows 6.1 Swift version matrix job. Defaults to false."
        default: false
      windows_6_1_build_command_options:
        type: string
        description: "The arguments passed to swift test in the Windows 6.1 Swift version matrix job."
        default: ""
      windows_6_2_enabled:
        type: boolean
        description: "Boolean to enable the Windows 6.2 Swift version matrix job. Defaults to false."
        default: false
      windows_6_2_build_command_options:
        type: string
        description: "The arguments passed to swift test in the Windows 6.2 Swift version matrix job."
        default: ""
      windows_nightly_release_enabled:
        type: boolean
        description: "Boolean to enable the Windows nightly (release/x) Swift version matrix job. Defaults to false."
        default: false
      windows_nightly_release_build_command_options:
        type: string
        description: "The arguments passed to swift test in the Windows nightly (release/x) Swift version matrix job."
        default: ""
      windows_nightly_main_enabled:
        type: boolean
        description: "Boolean to enable the Windows nightly (main) Swift version matrix job. Defaults to false."
        default: false
      windows_nightly_main_build_command_options:
        type: string
        description: "The arguments passed to swift test in the Windows nightly (main) Swift version matrix job."
        default: "-"
    secrets:
      PERSONAL_ACCESS_TOKEN:
        required: false

jobs:
  unit-tests-macos:
    name: Unit tests
    uses: hdtls/swift-ci/.github/workflows/unit_tests_macos.yml@main
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    with:
      macos_pre_build_command: ${{ inputs.macos_pre_build_command }}
      macos_build_command: ${{ inputs.macos_build_command }}
      macos_build_command_options: ${{ inputs.macos_build_command_options }}
      macos_5_9_enabled: ${{ inputs.macos_5_9_enabled }}
      macos_5_9_build_command_options: ${{ inputs.macos_5_9_build_command_options }}
      macos_5_10_enabled: ${{ inputs.macos_5_10_enabled }}
      macos_5_10_build_command_options: ${{ inputs.macos_5_10_build_command_options }}
      macos_6_0_enabled: ${{ inputs.macos_6_0_enabled }}
      macos_6_0_build_command_options: ${{ inputs.macos_6_0_build_command_options }}
      macos_6_1_enabled: ${{ inputs.macos_6_1_enabled }}
      macos_6_1_build_command_options: ${{ inputs.macos_6_1_build_command_options }}
      macos_6_2_enabled: ${{ inputs.macos_6_1_enabled }}
      macos_6_2_build_command_options: ${{ inputs.macos_6_1_build_command_options }}

  unit-tests-linux:
    name: Unit tests
    uses: hdtls/swift-ci/.github/workflows/unit_tests_linux.yml@main
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    with:
      linux_pre_build_command: ${{ inputs.linux_pre_build_command }}
      linux_build_command: ${{ inputs.linux_build_command }}
      linux_build_command_options: ${{ inputs.linux_build_command_options }}
      linux_5_9_enabled: ${{ inputs.linux_5_9_enabled }}
      linux_5_9_build_command_options: ${{ inputs.linux_5_9_build_command_options }}
      linux_5_10_enabled: ${{ inputs.linux_5_10_enabled }}
      linux_5_10_build_command_options: ${{ inputs.linux_5_10_build_command_options }}
      linux_6_0_enabled: ${{ inputs.linux_6_0_enabled }}
      linux_6_0_build_command_options: ${{ inputs.linux_6_0_build_command_options }}
      linux_6_1_enabled: ${{ inputs.linux_6_1_enabled }}
      linux_6_1_build_command_options: ${{ inputs.linux_6_1_build_command_options }}
      linux_6_2_enabled: ${{ inputs.linux_6_2_enabled }}
      linux_6_2_build_command_options: ${{ inputs.linux_6_2_build_command_options }}
      linux_nightly_release_enabled: ${{ inputs.linux_nightly_release_enabled }}
      linux_nightly_release_build_command_options: ${{ inputs.linux_nightly_release_build_command_options }}
      linux_nightly_main_enabled: ${{ inputs.linux_nightly_main_enabled }}
      linux_nightly_main_build_command_options: ${{ inputs.linux_nightly_main_build_command_options }}

  unit-tests-windows:
    name: Unit tests
    uses: hdtls/swift-ci/.github/workflows/unit_tests_windows.yml@main
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    with:
      windows_pre_build_command: ${{ inputs.windows_pre_build_command }}
      windows_build_command: ${{ inputs.windows_build_command }}
      windows_build_command_options: ${{ inputs.windows_build_command_options }}
      windows_6_0_enabled: ${{ inputs.windows_6_0_enabled }}
      windows_6_0_build_command_options: ${{ inputs.windows_6_0_build_command_options }}
      windows_6_1_enabled: ${{ inputs.windows_6_1_enabled }}
      windows_6_1_build_command_options: ${{ inputs.windows_6_1_build_command_options }}
      windows_6_2_enabled: ${{ inputs.windows_6_2_enabled }}
      windows_6_2_build_command_options: ${{ inputs.windows_6_2_build_command_options }}
      windows_nightly_release_enabled: ${{ inputs.windows_nightly_release_enabled }}
      windows_nightly_release_build_command_options: ${{ inputs.windows_nightly_release_build_command_options }}
      windows_nightly_main_enabled: ${{ inputs.windows_nightly_main_enabled }}
      windows_nightly_main_build_command_options: ${{ inputs.windows_nightly_main_build_command_options }}
