name: Unit tests (macOS)

on:
  workflow_call:
    inputs:
      macos_pre_build_command:
        type: string
        default: ""
      macos_build_command:
        type: string
        default: swift test
      macos_build_command_options:
        type: string
        description: "The default arguments passed to swift test in the macOS matrix job. override by versioned build_command_options."
        default: ""
      macos_5_9_runs-on:
        type: string
        description: "The runner for the matrix job using Swift 5.9, defaults to macos-14. Use commas to define multiple runners."
        default: "macos-14"
      macos_5_9_enabled:
        type: boolean
        description: "Boolean to enable the macOS Swift 5.9 (Xcode 15.2) matrix job. Defaults to false."
        default: false
      macos_5_9_build_command_options:
        type: string
        description: "The arguments passed to swift test in the macOS Swift 5.9 (Xcode 15.2) matrix job."
        default: ""
      macos_5_10_runs-on:
        type: string
        description: "The runner for the matrix job using Swift 5.10, defaults to macos-14. Use commas to define multiple runners."
        default: "macos-14"
      macos_5_10_enabled:
        type: boolean
        description: "Boolean to enable the macOS Swift 5.10 (Xcode 15.4) matrix job. Defaults to false."
        default: false
      macos_5_10_build_command_options:
        type: string
        description: "The arguments passed to swift test in the macOS Swift 5.10 (Xcode 15.4) matrix job."
        default: ""
      macos_6_0_runs-on:
        type: string
        description: "The runner for the matrix job using Swift 6.0, defaults to macos-15. Use commas to define multiple runners."
        default: "macos-15"
      macos_6_0_enabled:
        type: boolean
        description: "Boolean to enable the macOS Swift 6.0 (Xcode 16.2) matrix job. Defaults to false."
        default: false
      macos_6_0_build_command_options:
        type: string
        description: "The arguments passed to swift test in the macOS Swift 6.0 (Xcode 16.2) matrix job."
        default: ""
      macos_6_1_runs-on:
        type: string
        description: "The runner for the matrix job using Swift 6.1, defaults to macos-15. Use commas to define multiple runners."
        default: "macos-15"
      macos_6_1_enabled:
        type: boolean
        description: "Boolean to enable the macOS Swift 6.1 (Xcode 16.4) matrix job. Defaults to false."
        default: false
      macos_6_1_build_command_options:
        type: string
        description: "The arguments passed to swift test in the macOS Swift 6.1 (Xcode 16.4) matrix job."
        default: ""
      macos_6_2_runs-on:
        type: string
        description: "The runner for the matrix job using Swift 6.2, defaults to macos-26. Use commas to define multiple runners."
        default: "macos-26"
      macos_6_2_enabled:
        type: boolean
        description: "Boolean to enable the macOS Swift 6.2 (Xcode 26.0) matrix job. Defaults to false."
        default: false
      macos_6_2_build_command_options:
        type: string
        description: "The arguments passed to swift test in the macOS Swift 6.2 (Xcode 26.0) matrix job."
        default: ""
    secrets:
      PERSONAL_ACCESS_TOKEN:
        required: false

jobs:
  unit-tests-matrix-macos:
    name: Matrix (macOS)
    runs-on: ubuntu-latest
    outputs:
      tests-matrix: ${{ steps.tests-matrix.outputs.tests-matrix }}
    steps:
      - id: tests-matrix
        env:
          MATRIX_MACOS_PRE_BUILD_COMMAND: ${{ inputs.macos_pre_build_command }}
          MATRIX_MACOS_BUILD_COMMAND: ${{ inputs.macos_build_command}}
          MATRIX_MACOS_BUILD_COMMAND_OPTIONS: ${{ inputs.macos_build_command_options }}
          MATRIX_MACOS_5_9_RUNS_ON: ${{ inputs.macos_5_9_runs-on }}
          MATRIX_MACOS_5_9_ENABLED: ${{ inputs.macos_5_9_enabled }}
          MATRIX_MACOS_5_9_BUILD_COMMAND_OPTIONS: ${{ inputs.macos_5_9_build_command_options }}
          MATRIX_MACOS_5_10_RUNS_ON: ${{ inputs.macos_5_10_runs-on }}
          MATRIX_MACOS_5_10_ENABLED: ${{ inputs.macos_5_10_enabled }}
          MATRIX_MACOS_5_10_BUILD_COMMAND_OPTIONS: ${{ inputs.macos_5_10_build_command_options }}
          MATRIX_MACOS_6_0_RUNS_ON: ${{ inputs.macos_6_0_runs-on }}
          MATRIX_MACOS_6_0_ENABLED: ${{ inputs.macos_6_0_enabled }}
          MATRIX_MACOS_6_0_BUILD_COMMAND_OPTIONS: ${{ inputs.macos_6_0_build_command_options }}
          MATRIX_MACOS_6_1_RUNS_ON: ${{ inputs.macos_6_1_runs-on }}
          MATRIX_MACOS_6_1_ENABLED: ${{ inputs.macos_6_1_enabled }}
          MATRIX_MACOS_6_1_BUILD_COMMAND_OPTIONS: ${{ inputs.macos_6_1_build_command_options }}
          MATRIX_MACOS_6_2_RUNS_ON: ${{ inputs.macos_6_2_runs-on }}
          MATRIX_MACOS_6_2_ENABLED: ${{ inputs.macos_6_2_enabled }}
          MATRIX_MACOS_6_2_BUILD_COMMAND_OPTIONS: ${{ inputs.macos_6_2_build_command_options }}
        run: |
          echo "tests-matrix=$(curl -s --retry 3 https://raw.githubusercontent.com/hdtls/swift-ci/main/.github/workflows/scripts/generate_matrix.sh | bash)" >> "$GITHUB_OUTPUT"

  unit-tests-macos:
    name: Unix tests (macOS)
    needs: unit-tests-matrix-macos
    if: ${{ !contains(needs.unit-tests-matrix-macos.outputs.tests-matrix, '"definitions":[]') }}
    uses: hdtls/swift-ci/.github/workflows/matrix_macos.yml@main
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    with:
      name: Unix tests (macOS)
      matrix_string: "${{ needs.unit-tests-matrix-macos.outputs.tests-matrix }}"
